In [ ]:
# CREATING THE DATASET

In [ ]:

import pandas as pd

import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer

from scipy.sparse import hstack

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression

from sklearn.svm import SVR

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
# List of (mock) dreams
dreams = [
    "I find myself standing in an infinite classroom, my voice echoing endlessly. The students' faces blur into a sea of expectations. As I try to leave, the door vanishes, trapping me in a cycle of perpetual teaching. My knowledge becomes a burden I can't escape", "Walking through a sunlit meadow, I feel the warmth of the sun on my skin and the soft rustle of leaves. Birds sing a melody of peace. For the first time in months, the weight lifts, and my mind finds serenity amidst nature's embrace", " I am surrounded by screens displaying my achievements, each one demanding more. Notifications beep incessantly. I try to disconnect, but my devices fuse to my body, a constant reminder of my relentless drive and the world's unyielding expectations ", "In a vast hall, colors dance to an unseen orchestra. Each note brings a new hue, creating a symphony of light. My spirit is lifted by the beauty around me, a reminder that even amidst exhaustion, art can restore my soul", " I find myself on a dark, empty stage, the spotlight glaring. There is no audience, no applause, just overwhelming silence. I realize my fear of performing without validation, my successes feeling hollow without recognition",
    "Shelves upon shelves of books surround me, each containing a thought I have ever had. As I open one, memories flood back. I walk through my mental library, finding solace in the organized chaos of my mind, each book a testament to my intellect", " I wander through a city where the lights slowly dim. People move like shadows, their faces expressionless. The darkness encroaches, symbolizing my exhaustion. I struggle to keep a light alive within, knowing it's the key to escaping this bleak world", "The waves lap gently at my feet as I walk along an infinite beach. The horizon stretches endlessly. Each step feels lighter, the ocean's rhythm soothing my overworked mind. I feel a sense of infinite possibilities, a horizon of hope.", "In a room full of puzzle pieces, I try to fit them together. Each piece is a part of my life: career, relationships, dreams. The more I assemble, the clearer the picture of myself becomes, a mosaic of success and struggle.", "I climb a towering pile of papers and books, each step representing a task completed. The summit seems unreachable, but I continue, driven by an unseen force. At the peak, I find not exhaustion but a sense of accomplishment and perspective.",
    "I am in a crowd of people, all talking but no sound reaches my ears. I try to speak but can't hear my own voice. The silence is deafening, a manifestation of my feeling unheard despite my achievements.", " In a vibrant garden, flowers bloom with each step I take. The air is filled with the scent of fresh blossoms. I realize the garden represents my mind, capable of flourishing even after periods of drought and exhaustion.", " In a room with a massive clock, every tick feels like a heartbeat. The hands move rapidly, time slipping away. I try to stop it, feeling my life rush by too fast. The relentless pace mirrors my anxiety about losing precious moments.", "The walls of my home whisper my thoughts back to me, each one a reminder of my inner struggles and fears. I face each whisper, acknowledging them, and find that voicing my thoughts reduces their power over me.", " I run through an endless corridor lined with doors. Each door opens to a different aspect of my life, some bright, some dark. I realize that balance is key, and I need to close some doors to find peace.",
    "I float above the world, watching people live their lives. From this height, everything seems small and insignificant. I feel a sense of detachment but also clarity, understanding that my exhaustion is temporary and perspective is vital.", "Surrounded by friends, their laughter echoes around me. I join in, feeling a genuine connection and warmth. This dream reminds me of the importance of relationships and the joy that comes from shared moments of happiness.", "I explore a cave filled with glowing crystals, each one resonating with a different emotion. Touching them brings clarity and understanding. I navigate the cave, finding the crystals that help me reconnect with my core self.", " In a virtual reality world, I create scenarios of success and failure. I experience both vividly, learning to accept and learn from each. This controlled environment makes me realize that I the observer of my own behaviors and wishes and even mistakes. And I can learn from them. I feel with a sense of joy that I realized that intead of focusing too much on the actual experiments.", "I stand on the edge of a cliff, shouting into the abyss. My voice echoes back, distorted and unrecognizable. It's a reflection of my inner turmoil, the feeling of being lost and unheard. As the echoes fade, I realize the importance of finding my own voice amidst the chaos of life "
]

In [3]:
# Number of dreams
num_dreams = len(dreams)

In [4]:
# Generate additional variables (random numbers)
#strength = np.random.randint(0, 5, num_dreams)
#clarity = np.random.randint(0, 5, num_dreams)
#rumination = np.random.randint(0, 5, num_dreams)
#future_anxiety = np.random.randint(0, 5, num_dreams)

# Generate lists of additional variables (real numbers)
strength = ([0, 3, 0, 3, 1, 2, 2, 4, 3, 3, 0, 4, 0, 4, 3, 2, 4, 2, 4, 0])
clarity = [3, 4, 0, 3, 1, 3, 0, 1, 4, 4, 1, 2, 1, 2, 3, 4, 2, 4, 3, 1]
future_anxiety = [3, 0, 4, 1, 3, 1, 2, 0, 0, 1, 4, 1, 4, 2, 2, 1, 0, 0, 1, 2]

In [5]:
# Create DataFrame
data = {
    'Dream': dreams,
    'Strength': strength,
    'Clarity': clarity,
    'Future Anxiety': future_anxiety
}


In [6]:
df = pd.DataFrame(data)

# Save DataFrame to CSV
df.to_csv('dreams_data.csv', index=False)

print("CSV file 'dreams_data.csv' created successfully.")

CSV file 'dreams_data.csv' created successfully.


In [7]:
# Load the CSV file into a DataFrame
df = pd.read_csv('dreams_data.csv')

In [8]:
# Display the first few rows of the DataFrame
df.head()

Dream  Strength  Clarity  \
0  I find myself standing in an infinite classroo...         0        3   
1  Walking through a sunlit meadow, I feel the wa...         3        4   
2   I am surrounded by screens displaying my achi...         0        0   
3  In a vast hall, colors dance to an unseen orch...         3        3   
4   I find myself on a dark, empty stage, the spo...         1        1   

   Future Anxiety  
0               3  
1               0  
2               4  
3               1  
4               3

In [9]:
# Separate the text variable (X_text) from the numerical variables (X_numeric)
X_text = df['Dream']
X_numeric = df.drop('Dream', axis=1)
#print(X_text)
#print(X_numeric)

In [10]:
# Preprocess the Text Data: Perform text preprocessing steps such as tokenization, removing stopwords, and vectorization.

# Initialize the TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(stop_words='english')

# Fit and transform the text data
X_text_tfidf = tfidf_vectorizer.fit_transform(X_text).toarray()
X_text = X_text_tfidf

In [11]:
# Extract the predictors

X_strength = df[['Strength']].values
X_clarity = df[['Clarity']].values
X_anxiety = df[['Future Anxiety']].values

In [12]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_anxiety, X_text_tfidf, test_size=0.2, random_state=42)
print(X_train)
print(y_train)

[[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [2]
 [4]
 [1]
 [2]
 [3]
 [4]
 [0]
 [4]
 [2]
 [2]]
[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.16465806]]


In [13]:
# Initialize and train the model
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [14]:
# Predict on the testing data (Linear Regression Model)
y_pred = model.predict(X_test)
print(y_pred)
print(y_test)

# Evaluate the model
from sklearn.metrics import mean_squared_erro

# Calculate evaluation metrics
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r_squared = r2_score(y_test, y_pred)
rmse = np.sqrt(mse)
 
# Print the evaluation metrics
print("Mean Absolute Error (MAE):", mae)
print("Mean Squared Error (MSE):", mse)
print("R-squared (R²):", r_squared)
print("Root Mean Squared Error (RMSE):", rmse)

[[0.0154866  0.0056438  0.00712619 ... 0.03416338 0.0056438  0.04370997]
 [0.01002074 0.02015642 0.02545068 ... 0.02210572 0.02015642 0.00979733]
 [0.01184269 0.01531888 0.01934251 ... 0.02612494 0.01531888 0.02110154]
 [0.01002074 0.02015642 0.02545068 ... 0.02210572 0.02015642 0.00979733]]
[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.18771318]
 [0.         0.         0.         ... 0.         0.         0.        ]]
Mean Squared Error: 0.0034529493570737337


In [15]:
# SVR Model

# Ensure y_train is a 2D array
y_train = np.array(y_train)
if y_train.ndim == 1:
    y_train = y_train.reshape(-1, 1)


# Train the SVR model for each feature in the TF-IDF matrix
# We need to train one SVR model per TF-IDF feature
models = []
for i in range(X_text.shape[1]):
    svr_model = SVR(kernel='linear')
    svr_model.fit(X_train, y_train[:, i])
    models.append(svr_model)

# Make predictions
predictions = []
for i, model in enumerate(models):
    pred = model.predict(X_test)
    predictions.append(pred)
predictions = np.array(predictions).T

# Evaluate the model using Mean Squared Error
mse = mean_squared_error(y_test, predictions)
print(f'Mean Squared Error: {mse}')

Mean Squared Error: 0.01052263802192412


In [19]:
# Calculate evaluation metrics
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r_squared = r2_score(y_test, y_pred)
rmse = np.sqrt(mse)
 
# Print the evaluation metrics
print("Mean Absolute Error (MAE):", mae)
print("Mean Squared Error (MSE):", mse)
print("R-squared (R²):", r_squared)
print("Root Mean Squared Error (RMSE):", rmse)

Mean Absolute Error (MAE): 0.029440657088923818
Mean Squared Error (MSE): 0.0034529493570737337
R-squared (R²): -0.07087526779520523
Root Mean Squared Error (RMSE): 0.0587618018535318
